### ISSUE TITLE
Checkboxes withing call outs look a bit wonky

### ISSUE THREAD

**Issue by VisigothThermodynamics** [MFdev-coder/obsidian-feather#1]
Dear dev,

I'm relly enjoying your Feather theme! It's really pleasant to use. One thing I've noticed though is that check boxes come off a bit wonky with the theme. I was wondering if this was something that might see a change in future releases?

Your fan,
VisigothThermodynamics 

![billede](https://github.com/MFdev-coder/obsidian-feather/assets/145002698/640d999c-923d-4ed3-ac16-1881452dd7d9)

**Comment by zfmohammed** [comment]
Dear @VisigothThermodynamics ,
Great to hear that from you. I have done the necessary changes -

- Fixed the Issue You mentioned 
- Changed the navigation buttons
- Changed the dropdown list
- Made the buttons match the accent color

**Comment by zfmohammed** [comment]
If there are any queries or problems regarding the theme, Please let me know

Faraz XX
